export const DEFAULT_GAME_START_TIME_MILIS = 5000;
export const DEFAULT_GAME_END_TIME_MILIS = 10000;
export const DEFAULT_SLOT_ROTATION_MILIS = 50;

export const AWARD_FOR_ALL_MATCHING = 100;
export const AWARD_FOR_TWO_CONSECUTIVE = 20;
export const AWARD_FOR_TWO_MATCHING = 10;
